### ISSUE TITLE
Ios13 beta

### ISSUE THREAD

**Issue by bmctiger** [MediaGrabber/iOS-Workflow#8]
On ios13 beta get this error 
![7BB914FF-0FF2-411C-B99B-FE5E5EC112AA](https://user-images.githubusercontent.com/5333815/60410085-4ad0ee80-9b7b-11e9-98ae-11552f6ed9c5.png)

**Comment by sayem314** [comment]
Official beta version for iOS 13!

https://kutt.it/mg140b

If you are not on iOS beta then don’t use it.

**Comment by LiroyvH** [comment]
@sayem314: Thanks! It works, but for it to be a working sharing extension on some sites it has some issues because it also contains text. (Eg: funny video hosted at blabla - https://video.url/bla). I had to change allowed input to URL and Text and then add “Get URL from input” on top and then change the IF input contains Input to IF URL (magic variable) contains URL.

And now everything works as intended from widget, share extension and from Shortcuts app directly.

-edit- Ah correction, still doesn’t work entirely as intended. It now always demands clipboard.

**Comment by sayem314** [comment]
@CoreISP wait until iOS 13 public release of the stable version. Everything should be fine then!

**Comment by sayem314** [comment]
Beta 2 https://kutt.it/mg140b2

**Comment by clrmsc** [comment]
Dont work instagram downloading, pls fix it! TY!)

**Comment by JoePac5** [comment]
I keep getting “oops can’t download this file” it happens almost all the time. 
I’m running 1.4.0 Beta 2 on iOS 13 Beta 7

**Comment by sayem314** [comment]
Beta 3 https://kutt.it/mg140b3

**Comment by yoyoitsevan** [comment]
Beta 3 no longer works with iOS 13 beta. Currently on iOS 13.1 beta and I get a pop up that seems like it found video content, then finally an error. The same error comes from any of the 3 options it gives me for a video.
![4A4F83E1-CF3B-42E5-9BEF-99FB23A78AF3](https://user-images.githubusercontent.com/19396779/64650023-29e31000-d3ec-11e9-979d-adefe819c931.jpeg)
![DFBB1FDD-DB90-4C96-AEF1-AAB56CB7579E](https://user-images.githubusercontent.com/19396779/64650024-29e31000-d3ec-11e9-93be-da37c6ee89a0.jpeg)

**Comment by sayem314** [comment]
Beta 4
https://kutt.it/mg140b4

@yoyoitsevan this version should fix it

**Comment by AI0183** [comment]
This shortcuts is now working

**Comment by BreiteSeite** [comment]
> Beta 4
> https://kutt.it/mg140b4

This link doesn’t work anymore :(

**Comment by sayem314** [comment]
> > Beta 4
> > https://kutt.it/mg140b4
> 
> This link doesn’t work anymore :(

What's wrong with the link? Seems fine on my side.

**Comment by sayem314** [comment]
Updated readme
